'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/navbar.component'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'De Sean Ward | Fullstack Software Engineer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children} 
      </body>
    </html>
  )
}
