'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/navbar.component'
import TransitionEffect from '@/components/transition-effect/transition-effect.component'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>De Sean Ward | Fullstack Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"></link>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"></link>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </head>

      <body className={inter.className}>
        <Navbar />
        <TransitionEffect />
          {children} 
      </body>
    </html>
  )
}
